apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Chart.Name }}-secret
  labels:
    {{- include "sa-platform.labels" . | nindent 4 }}
  namespace: {{ .Values.global.namespace }}
spec:
  encryptedData:
    {{- range $key, $value := .Values.secretEnv }}
    {{ $key }}: {{ $value }}
    {{- end }}
