{{- if .Values.rbac.role.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "cluster-governance.fullname" . }}-role-binding
  namespace: {{ include "cluster-governance.namespaceName" . }}
  labels:
    {{- include "cluster-governance.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "cluster-governance.fullname" . }}-role
subjects:
  - kind: ServiceAccount
    name: {{ include "cluster-governance.serviceAccountName" . }}
    namespace: {{ include "cluster-governance.namespaceName" . }}
{{- end }}
