---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sa-platform-interactions-db
  namespace: sa-p5
spec:
  encryptedData:
    mongodb-replica-set-key: AgCaJ/Qzay2eRMfO3DYT3bs2Nlqvav4YEUQk3HFiZq/KnK3XnphOmfhTVPjE9aCXcb5vG6Eg7hkPfyLuaPuxaMkn1uhgRmwcpb7clICiuz/kbrsrOYxyK/MBS9kT+t0qpnsnSzWMvD39VTUDlTqbXyOraQKlFS97GniojgzPL6/Ske5FkSxfifu+T8mIsRLJdq+rc5gCxn/PUSP8B9E5SEmO2SbHbG30tbheFVGvrvB148kqF1bKJL0fgQgYU3tHbhqgCX0gnDez52p4xccAnnuUsiCW26pV5abc0PpGONRx5IlwFaP8p32XWhldwXPfFRC82i4iIE568lAzIfpm0etaD5h01jOp4aG6chI+gToIPZVatu5KbrlQ1h2VvRsBzIt4LPbUmgI0d7tvl6MxpkT8GyEY2JZY25HGkAfxsCyZsOMW5Q8fcTeuFTmhTWUe07vBysR9VkzyBa4FS2yx0zeg4WFmMwG1d3qXtRwsesmuTSdz5ULo0Rgl9++EsVmBqA/eUOwNniweX8E4nWbtcHkOS85yxgyFhSoA8GPq7gfcv2X/Xt7w3Imkt/DmytOoR/6A7H3xT4YpXnRGj0gaomNsnjOC4nTqofuHQ/ottASPIGj7BHt7AN5PR+C/v8p4P/1DJbtZFX6CwgZI5CIFCZKmZPoEZwWQC31hsn/G22m2xP7CuULxY4U2ZhrrDjGpXJxtKsRssjRcEOL1Zgk0
    mongodb-root-password: AgA7kQeGDILnt9RtEjyosk9kuoh1WDf4jaeCe+EpQMgv2yhfI/gJvJFMK/jv2oZqE/dJzD6xqVJjdJ4/eJgoz3MCq6GiivfeMnhLSGu9yVnrHzTj9OwvOZschISUg0oAyuLyq7qOKmuZ7CBaPm5KT1WGGU7giNCYjiNJQTFmOg/XaKPJqT10MEmkxIFZTrmhysKNcaGYBMoOJHWnVcfnoq8exHx42iZc5xfRHvXkgSN9/ZYhWDDZPhyTz5ae6vl6UOYpf2OJTorQbpwOZYI/oo1qRfw5v9CrKURKS2zovkr9dU/0qXyGp3v1hd2iJZW6O37v3loAmkwStvE1gIyKYyYksmfIQZCO8VNqxWu0Bqc+UGmSAr8TwlQ8JJZltScOmlSNsavtkSukvUbL87ACg1tbW6bLvIprVwNPJ18IYUPGFJKrsef0d140LcSWerC2tJvI6JFpz/MY7gW+UG2qg6vk+ZBRKUEOSVs3WiqdMK29iisG8ZjXiJSlolDuhnuUI+sXB5AAZjnbyf+49rCH7jBBJP4sNPTKzT0JuP7gYyrU29HOUcD462CRCSNumzaefsDXSsbdGxSu/whE/tPKtAhpHp8JYgEWi3i6BKQBuqsnHKR2uo4lTJhk8TOou6BP5po+m33fRUYGDwAU09pLpE5rUkiUiAxeLCsSMIaO/RVdVB+8XruP1gdGtc7/zuEiCoVQxzuanYdSR/6K1w==
  template:
    metadata:
      name: sa-platform-interactions-db
      namespace: sa-p5
    type: Opaque
