---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sa-platform-products-db
  namespace: sa-p5
spec:
  encryptedData:
    mongodb-replica-set-key: AgBq1e1nYdWdKWR1PaIPATakBzIvnoG6ki0yRSsUgG8ifTWlsaT0ukGGbARnnqTff8RDjLtLbZp/Nf4/PvLUBex+MRXycmgqTxcNrl94BTxICgbFlNd7OaVEVdDtd9huLMjzevK3wwcwM+egNDpPJitoH0msc0IEOA4xtEOGMNIjzkm7CUiFbOStKsiLZdsKSwS8oK9PjDH6dlil2yOwOFndetkSscsWtnBD2XECo37+NFXm2RARhRll/ImEGUdxuyG27n6p9+mEra6WGuB6J3u3tyEMPk8omrXeQF+lKeebFVBGbe07g52unCz+5ItNodPXPNBrNBybTtz0rv3piZfbVvLtcgZgUNxLgKI081L5N1Nr2fEtlv7NKycrOuKUmVEJE18PWFutcDue9wQshdkh/IseqdWxyLzMV7FbridRYRw14l/klF8FDgxUSgPFfXGxSECYw6jv/qGOpPPElr8M3h4do/w3F1ktfSBOTYTnQwZUfl7DN3AFjYl3dL6rjSxnND42zl0py0O24uN0ESh44RMkiBRSOjjQVYd9BHvsyhWA5pDwhYVoLXpmQfBsLbuf1zd/6iLob/f6S4fwMWBtautZl/CaS198xuoMui/m6BOtdqcBYP67QPt4k3vf5XshEfG7GMU/f8bfN5flGyIg0MSQ2HDxG07tJw6boUv5PnAefslJ+vDTJ2L1VEDGOUyEwa2sRq4SfATN9QVQ
    mongodb-root-password: AgBRAiXv3q1DmMWJuUO+72pt5GFGoh18gbzVwDICktgqO/f0uBWxxUZhybMB3odIbG/tkmZDorogqZlqMBLsLudhG5rk4A7Cqoz2y5YGPiT4YMPacgZc8L/fmxyeOAyy06yoWm3of5Pkm0vry55m1u4abS/sjhg1LpxPGd8dlPQEZPLrUUQWXBrpmn7HLbG8hhO1utt2g7ZSUSeMKz/csm8CgzCURXP/JaMrLiW0MEig5EAcUJwBkR/9c01cBtiV3IN6JA5E7MTFWpvTe0C6BkW/ngBspXDh7ekKL7OhSwmZN9nSORDwZxsVnz51CjVMpvA43WJsMx2J5wD8O0aHtecia+/0Xyifr1g1uAxdNWwqCgo02/jZlsjyRgKMo8xpUxLVFuHYiWaArtCm1sPnJk0FebQ2UgDKUOpzvbTDEh4+JuAytdJEuPL9b1VBSweFpPUcyRbIRI36d0aWiTTFurn/7JMMVd5ekhxWd8QI5dxaqEJmb5c2fW7yCo8PjGDBzZMnPxpSmcPZ1tKeXY0D9OuonbMKEKP8K0eAUs7zGpdKc+NU7BR0YZnmoX3I6RdKO9KaJozaniFaIboO3i0qX1U2cbQr0CpnzMyompeGrqemMPbQXL/DMWjAnE2qT7m2HLMA+Dye7AuSdqXwo/Oazreh+USNNbkQ/U4t2dLEu7ad2QJfayvoid+lHjSrR4+BMfZn+pLrIE0cA4PGtA==
  template:
    metadata:
      name: sa-platform-products-db
      namespace: sa-p5
    type: Opaque
