---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sa-platform-users-identity-db
  namespace: sa-p5
spec:
  encryptedData:
    mongodb-replica-set-key: AgAmodzKo8m8b0G+PiY7OcdEkBE0I0bTpypjk1PMtWba4eT0j0iUNZlFAs1sqINsx3sTRQfMcsFnSKvlvVXK24Ecf42YdIxNB0w0qnQbu1dTYldyhvlkocoSuri68YPce23HRzvbyu0lOldX5h6z+ZV6I36FqIxpW7eAe7qHNDn8VK4CN+nTwXtXw/z/Np97uL+eiQpC3SqKWIes2lQ0LqogFdplfjCuGzB8CzdCJUYj/MJ/V/lyNO6fI9fTIDlX/2RwXeJLvXIx6PE1q6A9kazbk9gthb5FYYN34B28OCSGdHCgPW1WkOP2H73xSzBS40Dy9xBQZ+hIOv5ovwzymdU9fVHxtE3xZTlsZ+uZUOhkYRZaop2d/pBqfiI1CspMOSc3wggp8n04l3Vb3SHGRPzP7PLNHwnuw3VyevWHv3H7FIFPBnaiqiPVrABhotQD2X5wUTt5Xalm13Zcjr0q8LSOw9e4z1rk66S9P5XSH1mzrzAxnV50lMGtDyIRBld4T6uBY/Y8+YiDm1huR1Oi5SHrR89Z2K927U37s0Gw6cFqkBc/Z32zFjsC3Hxhew/5AR04jzTbULrJ1tsyIgB49//339JJu4o3KjjRtQEWTRqOKrasgiAS2WjurZ2jL3bqXy1eBujwtW60Tyyzis8CKxLdKOobUYr+6zVeWMF/M80POqbV7ddkUoAh3KMGj7TIiOXFkY5v/bKXsx06/FMM
    mongodb-root-password: AgBEiXFzwIFb9CxecGFR2+NQpQdthecEzB2mP/m8A1gtEMae/h9wqswDskhcj///31ClZ663eJtgLThMpIJz69H5fZ+UoiZci2h3V6tPvZSybIbRk2bFbm0TtgPeZyMdQi9t8NTnsHkN8WKuF7v6vKH0WPDwutlGiUefOIq2ORSZGYB8aNfd+KKyeFwhUwxPvXfr+QYvKkK+sSw6CDRWBoUqCmAdaNkel2DQkGxqFR7VY/wYzmRYRa9i4XcjiFDESoYHdlWcjxjDwSiJ3J5UB/sNBbPmbpz+sEivMekwVoyOm0XbF01aRuceNeX44aBCNMGuIgFl7/+fRoc57Nh59nfPvGjKjl88L6UGLgAkzkItWnBr1r/5QPzemOUgIorejtCCmfaF/Tb9pBKK5ELQae1BPbguhG5e2BrxZJfNrhMTMO7vmW8MroICEkmd6Kz+cNQpoaeRaWrPLqzpMXeq8KrT10OZlh8JnVJK9FnR3hN/2lrZI1+oMkJl8+0Gp0dWWHqh6MNJvEbmPDTlU+fkSE4+jseGZzxUQIKwuQdm03y1FYPjPA8Wi+Fdt71hOXtE5xZztbDXTUBG/0zuHhuIyrPOUj1g0i/xSmm/t8+TtUCc5buJVrbb4qpi+0qF6uJf3xv2UAU2km5WHqBuw83vqACsnVskncJF7RX+0u9Y7jbtDCON5Y+jAniKXRHQZ10KWUTVeN+o0FlFReyAJg==
  template:
    metadata:
      name: sa-platform-users-identity-db
      namespace: sa-p5
    type: Opaque
