apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob-summary-db
  namespace: {{ .Values.global.namespace }}
spec:
  schedule: {{ required "cronjobs.summary.schedule es obligatorio" .Values.cronjobs.summary.schedule | quote }}
  concurrencyPolicy: Forbid
  backoffLimit: 2
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: job2-sa

          {{- if eq .Values.global.ghcr "yes" }}
          imagePullSecrets:
            - name: ghcr-secret
          {{- end}}

          containers:
            - name: tarea-cron2
              image: "{{ .Values.cronjobs.summary.image.repository }}:{{ .Values.cronjobs.summary.image.tag | default "latest" }}"
              imagePullPolicy: {{ .Values.cronjobs.summary.image.pullPolicy | default "IfNotPresent" }}
              resources:
                requests:
                  cpu: {{ .Values.cronjobs.summary.resources.requests.cpu | default "50m" | quote }}
                  memory: {{ .Values.cronjobs.summary.resources.requests.memory | default "64Mi" | quote }}
                limits:
                  cpu: {{ .Values.cronjobs.summary.resources.limits.cpu | default "100m" | quote }}
                  memory: {{ .Values.cronjobs.summary.resources.limits.memory | default "128Mi" | quote }}
              envFrom:
                - secretRef:
                    name: audit-logs-secret
                - configMapRef:
                    name: audit-logs-config
          restartPolicy: OnFailure
