apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: job2-rolebinding
  namespace: {{ .Values.global.namespace }}
subjects:
  - kind: ServiceAccount
    name: job2-sa
    namespace: {{ .Values.global.namespace }}
roleRef:
  kind: Role
  name: job2-role
  apiGroup: rbac.authorization.k8s.io
