apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-secret
  namespace: {{ .Values.global.namespace }}
spec:
  encryptedData:
    .dockerconfigjson: {{ .Values.ghcr.json }}
  template:
    type: kubernetes.io/dockerconfigjson
    metadata:
      name: ghcr-secret
      namespace: {{ .Values.global.namespace }}
