apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: "https://vmware-tanzu.github.io/helm-charts"
    chart: velero
    targetRevision: 12.0.0
    helm:
      values: |
        initContainers:
          - name: velero-plugin-for-gcp
            image: velero/velero-plugin-for-gcp:v1.14.0
            imagePullPolicy: IfNotPresent
            volumeMounts:
              - mountPath: /target
                name: plugins

        configuration:
          backupStorageLocation:
            - name: default
              provider: gcp
              bucket: "202300636-velero-backups"
              config:
                serviceAccount: "velero-backups-sa@project-613deddb-cfff-4117-851.iam.gserviceaccount.com"
          volumeSnapshotLocation:
            - name: default
              provider: gcp
              config:
                project: "project-613deddb-cfff-4117-851"

        credentials:
          useSecret: false

        serviceAccount:
          server:
            create: true
            name: velero
            annotations:
              iam.gke.io/gcp-service-account: "velero-backups-sa@project-613deddb-cfff-4117-851.iam.gserviceaccount.com"

  destination:
    server: "https://kubernetes.default.svc"
    namespace: velero
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
