apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    - repoURL: "https://kyverno.github.io/kyverno"
      chart: kyverno
      targetRevision: 3.8.2
      helm:
        parameters:
          - name: config.keep
            value: "false"
          - name: crds.keep
            value: "false"

    - repoURL: https://github.com/jemc2023/Practicas-SA-Manifests.git
      targetRevision: master
      path: kyverno-policies
      helm:
        valueFiles:
          - values.yaml

  destination:
    server: "https://kubernetes.default.svc"
    namespace: kyverno
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
